//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
    using System;
    using System.Reflection;


    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegisterViewModel
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterViewModel()
        {
        }

        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AskAbout.Resources.Models.Account.RegisterViewModel", typeof(RegisterViewModel).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong e-mail address.
        /// </summary>
        public static string EmailErr
        {
            get
            {
                return ResourceManager.GetString("EmailErr", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The email filed is required.
        /// </summary>
        public static string EmptyEmail
        {
            get
            {
                return ResourceManager.GetString("EmptyEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The login field is required.
        /// </summary>
        public static string EmptyLog
        {
            get
            {
                return ResourceManager.GetString("EmptyLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The password is required.
        /// </summary>
        public static string EmptyPass
        {
            get
            {
                return ResourceManager.GetString("EmptyPass", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The field must be at least {2} and at max {1} characters long.
        /// </summary>
        public static string LogPass
        {
            get
            {
                return ResourceManager.GetString("LogPass", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The password and confirmation password do not match.
        /// </summary>
        public static string Match
        {
            get
            {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
    }
}
