INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Авто, Мото')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Бизнес, Финансы')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Города и Страны')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Гороскопы, Магия, Гадания')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Досуг, Развлечения')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Еда, Кулинария')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Животные, Растения')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Знакомства, Любовь, Отношения')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Искусство и Культура')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Компьютерные и Видео игры')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Компьютеры, Связь')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Красота и Здоровье')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Наука, Техника, Языки')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Образование')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Общество, Политика, СМИ')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Программирование')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Путешествия, Туризм')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Работа, Карьера')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Семья, Дом, Дети')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Спорт')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Стиль, Мода, Звезды')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Товары и Услуги')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Философия, Непознанное')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Фотография, Видеосъемка')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Юмор')
INSERT INTO [dbo].[Topics] ([Name]) VALUES (N'Юридическая консультация')
