INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Авто, Мото', 1, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Бизнес, Финансы', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Города и Страны', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Гороскопы, Магия, Гадания', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Досуг, Развлечения', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Еда, Кулинария', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Животные, Растения', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Знакомства, Любовь, Отношения', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Искусство и Культура', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Компьютерные и Видео игры', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Компьютеры, Связь', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Красота и Здоровье', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Наука, Техника, Языки', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Образование', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Общество, Политика, СМИ', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Программирование', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Путешествия, Туризм', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Работа, Карьера', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Семья, Дом, Дети', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Спорт', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Стиль, Мода, Звезды', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Товары и Услуги', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Философия, Непознанное', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Фотография, Видеосъемка', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Юмор', 0, 0, 0, 0)
INSERT INTO [dbo].[Topics] ([Name], [QuestionsCount], [TopicRating], [RepliesCount], [UsersCount]) VALUES (N'Юридическая консультация', 0, 0, 0, 0)
